name: HomeWorkChecker

on:
  push:
    branches: [ " " ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  hw-checker-job:
    runs-on: ubuntu-latest
    steps:

      - name: Validate Pull Request title
        if: github.event_name == 'pull_request'
        run: |
          pr_title_regex="^[a-zA-Z-]+_[a-zA-Z-]+_hw([0-9]+)$"
          pr_title="${{ github.event.pull_request.title }}"
          if [[ $pr_title =~ $pr_title_regex ]]; then
            HW_NUMBER=${BASH_REMATCH[1]}
            echo "HW_NUMBER=$HW_NUMBER" >> $GITHUB_ENV
          else
            echo "Pull Request title expected in format <Surname>_<Name>_hw<N>"
            echo "Received: $pr_title"
            exit 1
          fi

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Filter only relevant homework files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          HW_NUMBER: ${{ env.HW_NUMBER }}
        run: |
          echo "Filtering changes for HW$HW_NUMBER"
          ALLOWED_DIR="*/hw$HW_NUMBER/*"
          FILTERED_FILES=()
          for file in $ALL_CHANGED_FILES; do
            if [[ $file == $ALLOWED_DIR ]]; then
              FILTERED_FILES+=("$file")
            fi
          done
          if [ ${#FILTERED_FILES[@]} -eq 0 ]; then
            echo "No valid files found for HW$HW_NUMBER. Exiting."
            exit 1
          fi
          echo "FILTERED_FILES=${FILTERED_FILES[@]}" >> $GITHUB_ENV

      - name: Call the action kochaika/nand2tetris-grader
        uses: kochaika/nand2tetris-grader@main
        with:
          dir: /github/workspace/${{ env.FILTERED_FILES }}
